// Douglas Gehring - 00243682
// Lorenzo Cernicchiaro - 00287718

#define AST_SYMBOL                      1
#define AST_ADD                         2
#define AST_SUB                         3
#define AST_MUL                         4
#define AST_DIV                         5
#define AST_DIF                         6
#define AST_EQ                          7
#define AST_GE                          8
#define AST_LE                          9
#define AST_GREATER_THAN                10
#define AST_LESS_THAN                   11
#define AST_ARRAY_ACCESS                12
#define AST_CMD_LIST                    13
#define AST_CMD_LIST_TAIL               14
#define AST_INT                         15
#define AST_FLOAT                       16
#define AST_READ                        17
#define AST_WHILE                       18
#define AST_FUNC_CALL                   19
#define AST_PARAMS_FUNC_CALL            20
#define AST_IF                          21
#define AST_ELSE                        22
#define AST_RETURN                      23
#define AST_PRINT_PARAM_LIST            24
#define AST_PRINT                       25
#define AST_FUNC_DEC                    26
#define AST_DEC_LIST                    27
#define AST_CMD_BLOCK                   28
#define AST_ASSIGNMENT                  29
#define AST_LITERAL_LIST                30
#define AST_LITERAL_LIST_TAIL           31
#define AST_INITIALIZATION              32
#define AST_OPTIONAL_INITIALIZATION     33
#define AST_GLOBAL_VARIABLE_DECLARATION 34
#define AST_GLOBAL_VECTOR_DECLARATION   35
#define AST_PARAM                       36
#define AST_OPTIONAL_PARAMS_LIST        37
#define AST_CHAR                        38
#define AST_OPTIONAL_INDEX              39
#define AST_AND                         40
#define AST_OR                          41
#define AST_NOT                         42
#define AST_BRACKETS_EXPR               43
